# -*- coding: utf-8 -*-
"""YouTube  Whisperer v1.5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/starpowertechnology/youtube-whisperer-v1-5.359edcb0-5539-451a-a8e4-5ad9fbf6281b.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260324/auto/storage/goog4_request%26X-Goog-Date%3D20260324T040947Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D0fde4bd42d3385b958d0a8188e48fa0f1216313b5bd2f21fb204f76948ea68c1b96538ade588a5a08e2fa325003a9a8142fc0095c6897964bc0f75795e0250faf4175c1daf9a1a5673b7800728bb88ae6f180fedbd475de4aed4aa3a1685284329156730f0ef3baa49f97c86d0289d5949ee99185387ed4b2185d7c1a873eebfe52d50867c4d610d643d24417540ff9756c47f37aadbbd6ab5bccc53fc04b3bc17d5a5c7d4239345647de3286d1e2bfeec120d6d83cef454f33a8316fae749883d657615d44965da6090524350bd62f5ea44f468c14b014dd93116f65f73729c4ededcea23c84df3d78fdcacfcc6a7c80a6ecc00c586274bd66ca525c7c1eb49
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
qwen_lm_qwen2_5_transformers_3b_1_path = kagglehub.model_download('qwen-lm/qwen2.5/Transformers/3b/1')

print('Data source import complete.')

"""# `***Starpower DevTools***`

*This just a lil youtube converter for a model nothing crazy .. but can be helpful if your looking to develop an uncommon RAG system.
I dont know about everyone else but i actually look for most information on youtube so it just seems reasonable for the model to do so also*
"""

# Install the necessary libraries for API access, downloading, and AI transcription
!pip install -q google-api-python-client yt-dlp openai-whisper
# FFmpeg is usually pre-installed on Kaggle, but we ensure it's available
!apt-get install -y ffmpeg

"""*For Youtube API Access*

If you need access to youtube you can go to this link below*

[https://console.cloud.google.com/apis/library/youtube.googleapis.com](http://)

# ***Manual Transcript Converter***

*Run the cell, type in a query & select the video you want to transcribe from the list.*
"""

import os
import sys
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import yt_dlp
import whisper
import torch



# Configuration
API_KEY = 'YOUR_YOUTUBE_API_KEY_HERE'  # <--- PASTE YOUR API KEY HERE
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'
WHISPER_MODEL_SIZE = 'medium' # Options: tiny, base, small, medium, large (requires GPU)

def search_youtube(query, max_results=5):
    """
    Step 2: Retrieve list of videos using the official YouTube Data API.
    Returns a list of dictionaries containing video title and ID.
    """
    try:
        youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=API_KEY)

        # Call the search.list method to retrieve results matching the specified query term.
        search_response = youtube.search().list(
            q=query,
            type='video',
            part='id,snippet',
            maxResults=max_results
        ).execute()

        videos = []
        for search_result in search_response.get('items', []):
            videos.append({
                'title': search_result['snippet']['title'],
                'videoId': search_result['id']['videoId'],
                'url': f"https://www.youtube.com/watch?v={search_result['id']['videoId']}"
            })
        return videos

    except HttpError as e:
        print(f"An HTTP error {e.resp.status} occurred:\n{e.content}")
        return []

def download_audio_wav(video_url, output_name="target_audio"):
    """
    Step 4: Download audio and convert to WAV using yt-dlp and FFmpeg.
    This ensures compatibility with Whisper.
    """
    print(f"\n[System] Downloading and converting {video_url}...")

    # Configure yt-dlp for best audio quality converted to wav
    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'wav',
            'preferredquality': '192',
        }],
        'outtmpl': output_name, # output filename pattern
        'quiet': True,
        'no_warnings': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([video_url])

        # Verify file creation (yt-dlp appends the extension)
        final_filename = f"{output_name}.wav"
        if os.path.exists(final_filename):
            print(f"[System] Audio saved to: {final_filename}")
            return final_filename
        else:
            raise FileNotFoundError("WAV file was not created successfully.")

    except Exception as e:
        print(f"[Error] Download failed: {e}")
        return None

def transcribe_audio(file_path):
    """
    Step 5: Convert WAV file into a transcript using OpenAI Whisper.
    """
    print(f"\n[System] Loading Whisper model ('{WHISPER_MODEL_SIZE}')...")

    # Check for GPU
    device = "cuda" if torch.cuda.is_available() else "cpu"
    if device == "cpu":
        print("[Warning] GPU not detected. Transcription will be slow.")

    try:
        model = whisper.load_model(WHISPER_MODEL_SIZE, device=device)
        print(f"[System] Transcribing audio (this may take a moment)...")

        # Transcribe
        result = model.transcribe(file_path)
        return result['text']

    except Exception as e:
        print(f"[Error] Transcription failed: {e}")
        return None

# --- Main Execution Pipeline ---

if __name__ == "__main__":
    if API_KEY == 'YOUR_YOUTUBE_API_KEY_HERE':
        print("[Error] Please insert your Google Cloud API Key in the configuration section.")
    else:
        # Step 1: Type a query
        user_query = input("Step 1: Enter your search query: ")

        # Step 2: Retrieve list
        print(f"\nSearching for '{user_query}'...")
        results = search_youtube(user_query)

        if results:
            # Display options
            print(f"\n--- Found {len(results)} Videos ---")
            for idx, video in enumerate(results):
                print(f"{idx + 1}. {video['title']}")

            # Step 3: Select video
            try:
                selection = int(input("\nStep 3: Select a video number (1-5): ")) - 1
                if 0 <= selection < len(results):
                    selected_video = results[selection]
                    print(f"Selected: {selected_video['title']}")

                    # Step 4: Convert to WAV
                    wav_file = download_audio_wav(selected_video['url'])

                    if wav_file:
                        # Step 5: Whisper Transcription
                        transcript = transcribe_audio(wav_file)

                        # End Results
                        print("\n" + "="*40)
                        print("FINAL TRANSCRIPTION")
                        print("="*40)
                        print(transcript.strip())
                        print("="*40)

                        # Cleanup (Optional)
                        # os.remove(wav_file)
                else:
                    print("[Error] Invalid selection.")
            except ValueError:
                print("[Error] Please enter a valid number.")
        else:
            print("[System] No videos found. Check your API quota or query.")

"""# ***Load Your Model***

*Im choosing qwen 2.5 3b because its free & easy to install .. doesnt take a long time .. but u can connect any model u just need to make sure that model is smart enough to handle a function calling tool intuitively for the autonomous setup*
"""

# Cell 3 — Starpower Runtime Config + Tool Aliases @v1.0

import os
import torch

# ---------- Device + dtype ----------
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = torch.float16 if DEVICE == "cuda" else torch.float32

# ---------- Qwen model selectors ----------
# Default HF model (works if internet is enabled)
QWEN_HF_ID = "Qwen/Qwen2.5-3B-Instruct"

# Optional: local Kaggle path (set this if you pinned a Kaggle Model/Dataset)
# You can also set an env var in Kaggle: QWEN_MODEL_PATH="/kaggle/input/<your-path>"
QWEN_MODEL_PATH = os.environ.get("QWEN_MODEL_PATH", "").strip()
if not QWEN_MODEL_PATH:
    QWEN_MODEL_PATH = None

# ---------- YouTube API key (optional, for search cell) ----------
# If you already hardcoded API_KEY elsewhere, this won't break it.
try:
    from kaggle_secrets import UserSecretsClient
    _user_secrets = UserSecretsClient()
    _yt_key = _user_secrets.get_secret("YOUTUBE_API_KEY")
    if _yt_key:
        API_KEY = _yt_key
except Exception:
    pass

# ---------- Tool alias patch (so your interceptor loop works) ----------
# Your loop calls: tool_download_audio_wav() and tool_transcribe_wav()
# But your manual cell defined: download_audio_wav() and transcribe_audio()

if "download_audio_wav" in globals():
    tool_download_audio_wav = download_audio_wav
else:
    raise NameError("download_audio_wav is not defined. Re-run / restore the cell that defines it.")

if "transcribe_audio" in globals():
    tool_transcribe_wav = transcribe_audio
else:
    raise NameError("transcribe_audio is not defined. Re-run / restore the cell that defines it.")

print(f"[runtime] DEVICE={DEVICE}  DTYPE={DTYPE}")
print(f"[runtime] QWEN_MODEL_PATH={QWEN_MODEL_PATH}")
print(f"[runtime] QWEN_HF_ID={QWEN_HF_ID}")

# Load Qwen 2.5 3B Instruct @v1.0

from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_ID = QWEN_MODEL_PATH if QWEN_MODEL_PATH else QWEN_HF_ID

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=DTYPE,
    device_map="auto" if DEVICE == "cuda" else None,
    trust_remote_code=True
)

model.eval()
print("[model] loaded:", MODEL_ID)

"""# ***Summarize With An LLM***

*This is a simple wrap you can add to a model & still have a normal conversation .. whenever you send a youtube video it transcribes it .. just know that a long video takes a while*
"""

# YT-LLM
import re

def generate_response(user_input, transcript=None):
    """
    Constructs the prompt and gets a response from Qwen.
    If a transcript exists, it injects it into the context transparently.
    """

    # 1. Build the System Context
    if transcript:
        system_msg = (
            "The user has provided a video link. "
            "Below is the transcript of that video. Use it to reply to the user accurately.\n\n"
            f"--- VIDEO TRANSCRIPT START ---\n{transcript}\n--- VIDEO TRANSCRIPT END ---\n"
        )
    else:
        system_msg = "You are a helpful assistant."

    # 2. Format for Qwen 2.5 (Chat Template)
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_input}
    ]

    # 3. Tokenize & Generate
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    model_inputs = tokenizer([text], return_tensors="pt").to(DEVICE)

    # (Print a little status so you know it's thinking)
    print("\n[🧠 Model] Reading and thinking...")

    generated_ids = model.generate(
        model_inputs.input_ids,
        max_new_tokens=512,
        temperature=0.7,
        do_sample=True
    )

    # 4. Decode
    # We slice off the input tokens to just get the new response
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    # Clean up (remove the prompt part if the model echoes it, though skip_special usually handles it)
    # For Qwen, usually we just want the last part, but 'response' here might contain the full convo depending on the tokenizer config.
    # A safe bet is to look for "assistant" or just print the whole thing if unsure.
    # Let's try to extract just the answer.
    if "assistant\n" in response:
        return response.split("assistant\n")[-1]
    return response

# --- MAIN INTERACTION LOOP ---
print("==========================================")
print("   STARPOWER ACTIVATED 🚀")
print("   Paste a YouTube link to have the model 'watch' it.")
print("   Type 'exit' to quit.")
print("==========================================\n")

while True:
    user_msg = input("You: ")

    if user_msg.lower() in ["exit", "quit"]:
        print("Starpower deactivated.")
        break

    # 1. SCAN: Look for YouTube Link
    # Regex catches 'youtube.com' or 'youtu.be'
    youtube_regex = r'(https?://(?:www\.)?(?:youtube\.com/watch\?v=|youtu\.be/)([\w-]+))'
    match = re.search(youtube_regex, user_msg)

    final_transcript = None

    if match:
        video_url = match.group(0)
        print(f"\n[👀 System] Detected Video Link: {video_url}")
        print("[⏳ System] Downloading and Transcribing... (This might take a sec)")

        try:
            # A. Download
            wav_path = tool_download_audio_wav(video_url)

            # B. Transcribe
            # Note: We use your tool_transcribe_wav from Cell 3
            final_transcript = tool_transcribe_wav(wav_path)

            print(f"[✅ System] Transcription Success! ({len(final_transcript)} chars)")

        except Exception as e:
            print(f"[❌ Error] Failed to process video: {e}")
            # We continue anyway, just without the transcript

    # 2. GENERATE: Send to Model
    response = generate_response(user_msg, final_transcript)

    print(f"\nStarpower: {response}\n")
    print("-" * 40)

"""# How It Works


*If I send a message with a youtube link the system will  transcribe it using the cells above*

*user message: "youtube link" -> convert to wav -> transcribe audio*

*once the audio is transcribed, it is sent to the model like shown below*

*input = (user message + transcript)*

*this way recieving a video will register to the model as recieving a transcript with the user input so it can respond naturally*
"""

# YT-LLM — Proactive {SearchYT(...)} Agent Chat @v1.1

import re
from threading import Thread
from transformers import TextIteratorStreamer

SYSTEM_PROMPT = """You are a research agent designed to search YouTube at your own will.

You can search youtube by typing in a query in the () for this function calling tool below:
{SearchYT(Insert-query-here)}

This will retrieve a list of videos matching your query, then you can select a video by choosing the number of the video. This will create a transcription that you will then read with the user input to give a response"""

# Match: {SearchYT( anything here )}
searchyt_pattern = re.compile(r"\{SearchYT\((.*?)\)\}", re.DOTALL)


def _qwen_chat(system_msg: str, user_input: str) -> str:
    """
    Low-level chat helper: send system + user to Qwen and return raw text.
    Streaming output so you can watch what it does in real time.
    """
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_input},
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(DEVICE)

    print("\n[🧠 Model] Reading and thinking...\n")

    streamer = TextIteratorStreamer(
        tokenizer,
        skip_prompt=True,
        skip_special_tokens=True
    )

    gen_kwargs = dict(
        **model_inputs,
        max_new_tokens=512,
        temperature=0.7,
        do_sample=True,
        streamer=streamer,
    )

    thread = Thread(target=model.generate, kwargs=gen_kwargs)
    thread.start()

    full_text = ""
    for token_text in streamer:
        print(token_text, end="", flush=True)
        full_text += token_text

    print()  # newline after stream
    thread.join()

    return full_text.strip()


def generate_response(user_input: str, transcript: str | None = None) -> str:
    """
    High-level wrapper.

    If transcript exists:
        - We KEEP your system prompt exactly as-is.
        - We send the model a single user message that is:
              (user input + transcript)
      so it reads both together instead of treating transcript as a separate turn.
    """
    if transcript:
        # (User input + transcript)
        combined = f"{user_input}\n\n{transcript}"
        system_msg = SYSTEM_PROMPT
        return _qwen_chat(system_msg, combined)
    else:
        system_msg = SYSTEM_PROMPT
        return _qwen_chat(system_msg, user_input)


print("==========================================")
print("   STARPOWER ACTIVATED 🚀")
print("   Ask anything. If Starpower needs it,")
print("   it will use {SearchYT(...)} to hit YouTube.")
print("   Type 'exit' to quit.")
print("==========================================\n")

while True:
    user_msg = input("You: ")

    if user_msg.lower() in ["exit", "quit"]:
        print("Starpower deactivated.")
        break

    # -------- FIRST PASS: let Qwen decide if it wants research --------
    raw_reply = generate_response(user_msg, transcript=None)

    # Look for a {SearchYT(...)} function call in the reply
    match = searchyt_pattern.search(raw_reply)

    if not match:
        # No research requested: just answer directly
        print(f"\nStarpower: {raw_reply}\n")
        print("-" * 40)
        continue

    # -------- TOOL CALL: YouTube search requested (single search only) --------
    search_query = match.group(1).strip()
    print("\n[🤖 Starpower] Requested YouTube research:")
    print(f"{ { 'SearchYT': search_query } }")  # just for visual confirmation
    print("[⏳ System] Searching YouTube...")

    try:
        videos = search_youtube(search_query, max_results=10)
    except Exception as e:
        print(f"[❌ Error] YouTube search failed: {e}")
        print(f"\nStarpower (fallback): {raw_reply}\n")
        print("-" * 40)
        continue

    if not videos:
        print("[❌ System] No videos found for that query.")
        print(f"\nStarpower (fallback): {raw_reply}\n")
        print("-" * 40)
        continue

    # Show the options so YOU can see what it had access to
    print(f"\n[📺 System] Top {len(videos)} results:")
    for idx, v in enumerate(videos, start=1):
        print(f"{idx}. {v['title']}  ({v['url']})")

    # For now we keep the same behavior as your previous dev tool:
    # auto-pick the top result (YouTube's best match)
    chosen_idx = 0
    chosen = videos[chosen_idx]
    print(f"\n[🎯 System] Watching video #{chosen_idx + 1}: {chosen['title']}")
    print("[⏳ System] Downloading and Transcribing... (This might take a sec)")

    try:
        wav_path = tool_download_audio_wav(chosen["url"])
        transcript = tool_transcribe_wav(wav_path)
        print(f"[✅ System] Transcription Success! ({len(transcript)} chars)")
    except Exception as e:
        print(f"[❌ Error] Failed to process video: {e}")
        print(f"\nStarpower (fallback): {raw_reply}\n")
        print("-" * 40)
        continue

    # -------- SECOND PASS: answer using (user input + transcript) --------
    # We do NOT allow another {SearchYT(...)} here — this pass is "answer mode".
    final_answer = generate_response(user_msg, transcript=transcript)

    print(f"\nStarpower: {final_answer}\n")
    print("-" * 40)
